// Code generated by Kitex v0.6.2. DO NOT EDIT.

package messageservice

import (
	"context"
	message "douyin/kitex_gen/message"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "MessageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"MessageList":   kitex.NewMethodInfo(messageListHandler, newMessageServiceMessageListArgs, newMessageServiceMessageListResult, false),
		"MessageAction": kitex.NewMethodInfo(messageActionHandler, newMessageServiceMessageActionArgs, newMessageServiceMessageActionResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func messageListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceMessageListArgs)
	realResult := result.(*message.MessageServiceMessageListResult)
	success, err := handler.(message.MessageService).MessageList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceMessageListArgs() interface{} {
	return message.NewMessageServiceMessageListArgs()
}

func newMessageServiceMessageListResult() interface{} {
	return message.NewMessageServiceMessageListResult()
}

func messageActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceMessageActionArgs)
	realResult := result.(*message.MessageServiceMessageActionResult)
	success, err := handler.(message.MessageService).MessageAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceMessageActionArgs() interface{} {
	return message.NewMessageServiceMessageActionArgs()
}

func newMessageServiceMessageActionResult() interface{} {
	return message.NewMessageServiceMessageActionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) MessageList(ctx context.Context, req *message.MessageListRequest) (r *message.MessageListResponse, err error) {
	var _args message.MessageServiceMessageListArgs
	_args.Req = req
	var _result message.MessageServiceMessageListResult
	if err = p.c.Call(ctx, "MessageList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MessageAction(ctx context.Context, req *message.MessageActionRequest) (r *message.MessageActionResponse, err error) {
	var _args message.MessageServiceMessageActionArgs
	_args.Req = req
	var _result message.MessageServiceMessageActionResult
	if err = p.c.Call(ctx, "MessageAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
