// Code generated by Kitex v0.6.2. DO NOT EDIT.

package favoriteservice

import (
	"context"
	favorite "douyin/kitex_gen/favorite"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return favoriteServiceServiceInfo
}

var favoriteServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FavoriteService"
	handlerType := (*favorite.FavoriteService)(nil)
	methods := map[string]kitex.MethodInfo{
		"FavoriteAction":       kitex.NewMethodInfo(favoriteActionHandler, newFavoriteServiceFavoriteActionArgs, newFavoriteServiceFavoriteActionResult, false),
		"FavoriteCount":        kitex.NewMethodInfo(favoriteCountHandler, newFavoriteServiceFavoriteCountArgs, newFavoriteServiceFavoriteCountResult, false),
		"FavoriteExist":        kitex.NewMethodInfo(favoriteExistHandler, newFavoriteServiceFavoriteExistArgs, newFavoriteServiceFavoriteExistResult, false),
		"FavoriteCountOfVideo": kitex.NewMethodInfo(favoriteCountOfVideoHandler, newFavoriteServiceFavoriteCountOfVideoArgs, newFavoriteServiceFavoriteCountOfVideoResult, false),
		"FavoriteVideoList":    kitex.NewMethodInfo(favoriteVideoListHandler, newFavoriteServiceFavoriteVideoListArgs, newFavoriteServiceFavoriteVideoListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "favorite",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func favoriteActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteActionArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteActionResult)
	success, err := handler.(favorite.FavoriteService).FavoriteAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteActionArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteActionArgs()
}

func newFavoriteServiceFavoriteActionResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteActionResult()
}

func favoriteCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteCountArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteCountResult)
	success, err := handler.(favorite.FavoriteService).FavoriteCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteCountArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteCountArgs()
}

func newFavoriteServiceFavoriteCountResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteCountResult()
}

func favoriteExistHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteExistArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteExistResult)
	success, err := handler.(favorite.FavoriteService).FavoriteExist(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteExistArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteExistArgs()
}

func newFavoriteServiceFavoriteExistResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteExistResult()
}

func favoriteCountOfVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteCountOfVideoArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteCountOfVideoResult)
	success, err := handler.(favorite.FavoriteService).FavoriteCountOfVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteCountOfVideoArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteCountOfVideoArgs()
}

func newFavoriteServiceFavoriteCountOfVideoResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteCountOfVideoResult()
}

func favoriteVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*favorite.FavoriteServiceFavoriteVideoListArgs)
	realResult := result.(*favorite.FavoriteServiceFavoriteVideoListResult)
	success, err := handler.(favorite.FavoriteService).FavoriteVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFavoriteServiceFavoriteVideoListArgs() interface{} {
	return favorite.NewFavoriteServiceFavoriteVideoListArgs()
}

func newFavoriteServiceFavoriteVideoListResult() interface{} {
	return favorite.NewFavoriteServiceFavoriteVideoListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FavoriteAction(ctx context.Context, req *favorite.FavoriteActionRequest) (r *favorite.FavoriteActionResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteActionArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteActionResult
	if err = p.c.Call(ctx, "FavoriteAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteCount(ctx context.Context, req *favorite.FavoriteCountRequest) (r *favorite.FavoriteCountResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteCountArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteCountResult
	if err = p.c.Call(ctx, "FavoriteCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteExist(ctx context.Context, req *favorite.FavoriteExistRequest) (r *favorite.FavoriteExistResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteExistArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteExistResult
	if err = p.c.Call(ctx, "FavoriteExist", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteCountOfVideo(ctx context.Context, req *favorite.FavoriteCountOfVideoRequest) (r *favorite.FavoriteCountOfVideoResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteCountOfVideoArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteCountOfVideoResult
	if err = p.c.Call(ctx, "FavoriteCountOfVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FavoriteVideoList(ctx context.Context, req *favorite.FavoriteVideoListRequest) (r *favorite.FavoriteVideoListResponse, err error) {
	var _args favorite.FavoriteServiceFavoriteVideoListArgs
	_args.Req = req
	var _result favorite.FavoriteServiceFavoriteVideoListResult
	if err = p.c.Call(ctx, "FavoriteVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
