// Code generated by Kitex v0.6.2. DO NOT EDIT.

package publishservice

import (
	"context"
	publish "douyin/kitex_gen/publish"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishAction(ctx context.Context, req *publish.PublishActionRequest, callOptions ...callopt.Option) (r *publish.PublishActionResponse, err error)
	PublishCount(ctx context.Context, req *publish.PublishCountRequest, callOptions ...callopt.Option) (r *publish.PublishCountResponse, err error)
	PublishList(ctx context.Context, req *publish.PublishListRequest, callOptions ...callopt.Option) (r *publish.PublishListResponse, err error)
	PublishExist(ctx context.Context, req *publish.PublishExistRequest, callOptions ...callopt.Option) (r *publish.PublishExistResponse, err error)
	PublishInfo(ctx context.Context, req *publish.PublishInfoRequest, callOptions ...callopt.Option) (r *publish.PublishInfoResponse, err error)
	PublishVideoList(ctx context.Context, req *publish.PublishVideoListRequest, callOptions ...callopt.Option) (r *publish.PublishVideoListResponse, err error)
	PublishListByLastTime(ctx context.Context, req *publish.PublishListByLastTimeRequest, callOptions ...callopt.Option) (r *publish.PublishListByLastTimeResponse, err error)
	FeedAction(ctx context.Context, req *publish.FeedActionRequest, callOptions ...callopt.Option) (r *publish.FeedActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kPublishServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPublishServiceClient struct {
	*kClient
}

func (p *kPublishServiceClient) PublishAction(ctx context.Context, req *publish.PublishActionRequest, callOptions ...callopt.Option) (r *publish.PublishActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishAction(ctx, req)
}

func (p *kPublishServiceClient) PublishCount(ctx context.Context, req *publish.PublishCountRequest, callOptions ...callopt.Option) (r *publish.PublishCountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishCount(ctx, req)
}

func (p *kPublishServiceClient) PublishList(ctx context.Context, req *publish.PublishListRequest, callOptions ...callopt.Option) (r *publish.PublishListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishList(ctx, req)
}

func (p *kPublishServiceClient) PublishExist(ctx context.Context, req *publish.PublishExistRequest, callOptions ...callopt.Option) (r *publish.PublishExistResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishExist(ctx, req)
}

func (p *kPublishServiceClient) PublishInfo(ctx context.Context, req *publish.PublishInfoRequest, callOptions ...callopt.Option) (r *publish.PublishInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishInfo(ctx, req)
}

func (p *kPublishServiceClient) PublishVideoList(ctx context.Context, req *publish.PublishVideoListRequest, callOptions ...callopt.Option) (r *publish.PublishVideoListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishVideoList(ctx, req)
}

func (p *kPublishServiceClient) PublishListByLastTime(ctx context.Context, req *publish.PublishListByLastTimeRequest, callOptions ...callopt.Option) (r *publish.PublishListByLastTimeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishListByLastTime(ctx, req)
}

func (p *kPublishServiceClient) FeedAction(ctx context.Context, req *publish.FeedActionRequest, callOptions ...callopt.Option) (r *publish.FeedActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FeedAction(ctx, req)
}
